services:
  postgres:
    container_name: bloodbuddy-db
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: himanshu
      POSTGRES_DB: bloodbuddy
      POSTGRES_PASSWORD: "1234"


volumes:
  postgres_data: