// This file was generated by Prisma
import { defineConfig, env } from "prisma/config";

// In hosted environments (e.g. Render), DATABASE_URL is usually injected.
// Locally, fall back to .env if DATABASE_URL is not already set.
if (!process.env.DATABASE_URL) {
  try {
    const dotenv = await import("dotenv");
    dotenv.config();
  } catch {
    // Ignore when dotenv is unavailable; Prisma will report missing DATABASE_URL.
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
